#!/usr/bin/env python3
"""Rebuild a hosted planner database: schema from code, rows from a dump.

**Why this exists rather than `pg_dump | psql`.** The schema is not a file — it is
generated by `travel_planner.pgstore.postgres_schema()` from `store.SCHEMA`, which is
what keeps the two backends from drifting (`supabase/MIGRATION.md`). Restoring from a
structure dump would reintroduce the second source of truth that file argues against. So
structure comes from the code and only rows come from the dump.

Usage, with the target URL passed explicitly and never read from the environment:

    uv run --locked python scripts/restore_hosted_database.py \
        --url "postgresql://…" --rows data/supabase-rows-2026-09-03.sql.gz

`--dry-run` reports what it would do and writes nothing. The restore refuses a target
that already holds planner rows unless `--force` is given, because running it twice
against a live database would duplicate every row it could and fail on the rest.
"""

from __future__ import annotations

import argparse
import gzip
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from travel_planner.pgstore import normalise_url, postgres_schema  # noqa: E402
from travel_planner.store import SCHEMA_VERSION  # noqa: E402

#: Order matters: a child table cannot be loaded before the row it references. Derived
#: from the dump's own order would be alphabetical, which puts `candidate_choices` before
#: `trips` and fails the foreign key.
PARENTS_FIRST = (
    "schema_meta", "trips", "trip_setups", "discovery_runs", "candidate_choices",
    "plan_versions", "active_plans", "optimization_previews", "comfort_acceptances",
    "place_evidence", "trip_evidence", "route_snapshots", "provider_cache",
    "checklist_items", "cost_items", "split_rows", "split_settled_markers",
    "paid_usage", "paid_usage_cap", "trip_deletions", "jobs", "plan_revisions",
    "exchange_rate_snapshots", "schema_migrations", "migrations",
)


def blocks(path: Path) -> list[tuple[str, str]]:
    """Every `COPY "table" FROM stdin;` block in the dump, as (table, tab-separated body)."""

    opener = gzip.open if path.suffix == ".gz" else open
    found: list[tuple[str, str]] = []
    table, body = None, []
    with opener(path, "rt", encoding="utf-8") as handle:
        for line in handle:
            if line.startswith('COPY "') and "FROM stdin" in line:
                table = line.split('"')[1]
                body = []
                continue
            if table is not None:
                if line.startswith("\\."):
                    found.append((table, "".join(body)))
                    table, body = None, []
                else:
                    body.append(line)
    return found


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", required=True, help="target Postgres URL")
    parser.add_argument("--rows", type=Path, help="row dump written by the backup step")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--force", action="store_true",
                        help="load rows even if the target already has trips")
    args = parser.parse_args()

    import psycopg

    url = normalise_url(args.url)
    found = blocks(args.rows) if args.rows else []
    if args.rows and not found:
        print(f"FAILED: no COPY blocks in {args.rows}", file=sys.stderr)
        return 1

    print(f"target      : {url.rsplit('@', 1)[-1].split('?')[0]}")
    print(f"schema      : generated at SCHEMA_VERSION {SCHEMA_VERSION}")
    print(f"row blocks  : {len(found)}")
    by_table = dict(found)
    # The order the real load uses, so a dry run shows what would actually happen
    # rather than the dump's alphabetical order — which puts `candidate_choices`
    # before `trips` and would fail the foreign key.
    ordered = [t for t in PARENTS_FIRST if t in by_table]
    ordered += [t for t in by_table if t not in PARENTS_FIRST]
    if args.dry_run:
        for table in ordered:
            print(f"  would load {table:26} {by_table[table].count(chr(10)):6} rows")
        return 0

    with psycopg.connect(url, connect_timeout=30, autocommit=False) as conn:
        cur = conn.cursor()
        cur.execute(postgres_schema())
        conn.commit()
        print("schema applied")

        cur.execute("select to_regclass('public.trips') is not null")
        if cur.fetchone()[0]:
            cur.execute("select count(*) from trips")
            existing = cur.fetchone()[0]
            if existing and not args.force:
                print(f"REFUSED: target already holds {existing} trip(s); pass --force to load anyway",
                      file=sys.stderr)
                return 1

        # The immutability triggers refuse the very rows being restored, so they are
        # disabled for the load and put back in the same transaction. `session_replication_role`
        # is the supported way and needs no DDL on the triggers themselves.
        cur.execute("set session_replication_role = replica")
        loaded = 0
        for table in ordered:
            body = by_table[table]
            if not body.strip():
                continue
            with cur.copy(f'COPY "{table}" FROM STDIN (FORMAT text)') as copy:
                copy.write(body)
            n = body.count("\n")
            loaded += n
            print(f"  loaded {table:26} {n:6} rows")
        cur.execute("set session_replication_role = origin")
        conn.commit()
        print(f"restored {loaded} rows into {len(ordered)} tables")

        cur.execute("select value from schema_meta where key = 'schema_version'")
        row = cur.fetchone()
        print(f"schema_version now: {row[0] if row else '(unset)'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
