"""Every user-facing string, keyed by language.

The core emits stable codes; this module maps code to language to text, so
switching language can never change ranking, scheduling, or the active plan.
Both `en` and `th` must carry the same keys; a test asserts that.
"""

from __future__ import annotations


TEXT = {
    "en": {
        "title": "Personal Travel Planner",
        "caption": "Local POC · your structured trip data stays on this computer",
        "new_trip": "Start a trip",
        "trip_name": "Trip name (optional)",
        "destination": "Destination",
        "mode": "Planning mode",
        "explore_first": "Explore first",
        "ready_to_schedule": "Ready to schedule",
        "create": "Create trip",
        "created": "Trip saved.",
        "destination_required": "Destination is required.",
        "saved_trips": "Saved trips",
        "resume": "Resume trip",
        "status": "Status",
        "draft": "Draft",
        "mode_label": "Mode",
        "active_plan": "Active plan version",
        "no_plan": "No itinerary has been generated. This screen only prepares and discovers places.",
        "empty": "Create your first trip to begin.",
        "setup": "Trip setup",
        "setup_help": "Save a draft anytime. Confirm before the app makes a discovery request.",
        "trip_basics": "1 · Trip basics",
        "dates_known": "Travel dates known",
        "start_date": "Start date",
        "end_date": "End date",
        "arrival_known": "Approximate arrival time known",
        "arrival_time": "Arrival time",
        "departure_known": "Approximate departure time known",
        "departure_time": "Departure time",
        "accommodation": "Accommodation",
        "owner_style": "2 · Owner trip style",
        "owner_age": "Owner age (0 = not set)",
        "main_style": "Main style · choose at least one",
        "also_enjoy": "Also enjoy",
        "avoid": "Avoid",
        "comfort": "Comfort preferences",
        "description": "Extra detail or nuance (optional)",
        "travellers": "3 · Travellers",
        "member_count": "Additional travellers",
        "member": "Traveller",
        "member_name": "Nickname / label",
        "member_age": "Age (0 = not set)",
        "member_tags": "Optional preference tags",
        "member_notes": "Optional notes",
        "member_must": "Must respect · one confirmed need per line",
        "requirements": "4 · Must respect",
        "owner_must": "Only genuine non-negotiables · one per line (optional)",
        "save_draft": "Save draft",
        "confirm": "Confirm setup",
        "draft_saved": "Draft setup saved locally. No provider was called.",
        "confirmed": "Setup confirmed. Discovery is now available.",
        "main_required": "Choose at least one Main style before confirmation.",
        "review": "5 · Review",
        "setup_state": "Setup state",
        "draft_setup": "Draft setup",
        "confirmed_setup": "Confirmed for discovery",
        "people": "People",
        "preferences": "Owner tags",
        "no_dates": "Dates are still optional; results cannot be treated as a dated timetable.",
        "discover_title": "Broad attraction discovery",
        "discover_help": "Runs only when you click. It uses a bounded worldwide OpenStreetMap baseline, cached for 7 days. Results are broad, not exhaustive.",
        "discover": "Discover attractions",
        "refresh": "Refresh provider data",
        "discovering": "Collecting the broad baseline…",
        "discovery_saved": "Discovery result saved.",
        "coverage": "Coverage report",
        "provider_status": "Provider status",
        # A provider outage is not the same thing as a plan that cannot be built,
        # so these carry their own words rather than borrowing the variant labels.
        "provider_verified": "Verified",
        "provider_stale": "Stale",
        "provider_unavailable": "Unavailable",
        "provider_error": "Error",
        "candidates": "Candidates",
        "duplicates": "Merged duplicates",
        "cells": "Geographic cells",
        "unranked": "Baseline only: preferences have not ranked or filtered these candidates.",
        "stale_setup": "This result belongs to an older setup. It remains visible, but confirm and discover again before ranking.",
        "provider_gap": "The provider could not return a current catalog. Your setup is safe; the evidence gap is shown below.",
        "no_candidates": "No usable candidates were returned. Check the coverage gaps and retry later.",
        "name": "Name",
        "local_name": "Local name",
        "category": "Category",
        "opening": "Opening evidence",
        "source": "Source",
        "details": "Full normalized coverage details",
        "osm_notice": "OpenStreetMap public services are for low-volume, user-triggered personal use; this app identifies itself, caches identical requests, and does not run autocomplete.",
        "ranking_title": "Personalized place cards",
        "ranking_help": "The score orders cards; it is not a guarantee. Missing route, crowd, rating, holiday-hour, and best-time evidence stays visible and neutral.",
        "ranking_wait": "Confirm the current setup and complete discovery before ranking.",
        "lane": "Card lane",
        "main_queue": "For your trip",
        "city_icons": "City Icons",
        "worth_it_if": "Worth It If…",
        "local_alternatives": "Local Alternatives",
        "browse_all": "Browse All",
        "select_card": "Choose a card",
        "no_lane_cards": "No cards currently qualify for this lane.",
        "score": "Score",
        "duration": "Visit estimate",
        "minutes": "min",
        "planner_estimate": "Planner category estimate; not venue-confirmed",
        "feasibility": "Feasibility",
        "not_evaluated": "Not evaluated until optimizer",
        "why": "Why shown",
        "pros": "Pros",
        "cons": "Cons / evidence gaps",
        "card_detail": "Why shown, pros, and evidence gaps",
        "breakdown": "30/20/20/10/15/5 score breakdown",
        "dimension": "Dimension",
        "points": "Points",
        "maximum": "Maximum",
        "deductions": "Named deductions",
        "no_deductions": "No evidence-backed deduction",
        "matched_tags": "Matched tags",
        "group_weights": "Group weights and learned signals",
        "choice": "Your choice",
        "must_do": "Must do",
        "interested": "Interested",
        "maybe": "Maybe",
        "not_for_trip": "Not for trip",
        "rejection_reason": "Optional reason for Not for trip",
        "no_reason": "No reason",
        "choice_saved": "Choice saved. Unseen cards were reordered; Browse All still retains everything.",
        "current_choice": "Current choice",
        "clear_choice": "Clear choice",
        "choice_cleared": "Choice cleared.",
        "exploration_card": "Protected exploration card",
        "icon_card": "Prominent landmark evidence",
        "source_rating": "Source rating",
        "not_enriched": "Not enriched yet",
        "route_effort": "Route / walking effort",
        "not_routed": "Not routed yet",
        "browse_notice": "Every current canonical candidate is retained here, including rated and low-scoring places.",
        "reconciliation": "Selected-place reconciliation",
        "reconciliation_help": "Nothing selected disappears. These card choices remain pending until you run the whole-trip optimizer below.",
        "no_selected": "No Must do or Interested places yet.",
        "pending_optimizer": "Pending optimizer",
        "present_latest": "In latest discovery",
        "next_step": "Next step",
        "run_optimizer": "Run whole-trip optimizer below",
        "all_choices": "All saved choices",
        "formula_note": "Neutral partial points mean evidence is missing—not that the place is average in reality.",
        "photo_source": "Open-data photo reference",
        "photo_unavailable": "No permitted photo reference is available yet.",
        "optimizer_title": "Whole-trip optimizer",
        "optimizer_help": "Uses all selected places across all dates. It may swap days or order, but it cannot invent routes, opening hours, access, or locks.",
        "generate_plan": "Generate / refresh three variants",
        "optimizing": "Optimizing the complete trip…",
        "preview_saved": "Plan preview saved locally.",
        "choose_before_plan": "Choose at least one Must do, Interested, or Maybe place first.",
        "stay_recommendation": "Dates are not fixed yet — compare suggested stay lengths",
        "stay_option": "Stay style",
        "days": "Days",
        "daily_capacity": "Planned daily capacity",
        "variant": "Plan variant",
        "best_balance": "Best balance",
        "relaxed": "Relaxed",
        "more_highlights": "More highlights",
        "ready": "Ready",
        "provisional": "Provisional / needs acceptance",
        "unavailable": "Unavailable",
        "scheduled_visits": "Visits",
        "travel_minutes": "Travel",
        "walking_minutes": "Walking",
        "plain_walking_minutes": "Plain walking",
        "buffer_minutes": "Buffers",
        "optimizer_warning": "Warnings and evidence gaps",
        "optimizer_reconciliation": "Final selected-place reconciliation",
        "fits": "Fits",
        "fits_with_tradeoff": "Fits with tradeoff",
        "cannot_currently_fit": "Cannot currently fit",
        "reason": "Reason",
        "consequence": "Consequence / smallest next step",
        "timeline": "Validated timeline",
        "item_type": "Type",
        "start": "Start",
        "end": "End",
        "place_or_leg": "Place / leg",
        "activate_plan": "Use this as active plan",
        "plan_activated": "Validated plan activated.",
        "activation_disabled": "Only a fully validated Ready variant can become active.",
        "no_schedule": "No selected visit can be scheduled safely with the current evidence.",
        "greedy_check": "Whole-trip result equals or improves the day-greedy baseline",
        "optimizer_limit": "Optimization stopped at its safe limit; only the validated incumbent is shown.",
        "use_title": "Active plan",
        "use_help": "One export snapshot feeds this view; posters, PDF, and Excel will read the same numbers.",
        "no_active_plan": "No plan is active yet. Activate a validated variant above.",
        "superseded_plan": "This is an older plan version. The active plan has moved on.",
        "exported_at": "Snapshot built",
        "readiness": "Readiness",
        "action_needed": "Action needed",
        "verification_needed": "Verification needed",
        "state_confirmed": "✅ Confirmed",
        "state_recheck": "🕒 Recheck",
        "state_tradeoff_accepted": "⚖️ Tradeoff accepted",
        "state_unverified_conflict": "⚠️ Unverified / conflict",
        "state_locked": "🔒 Locked",
        "highest_risk": "Highest risk today",
        "tab_map": "Map",
        "visit_minutes": "At places",
        "rewarding_walking_minutes": "Rewarding walking",
        "stop": "Stop",
        "travel_mode": "Mode",
        "walk_portion": "Walking portion",
        "distance": "Distance",
        "transfers": "Transfers",
        "boarding_buffer": "Boarding buffer",
        "sightseeing_walk": "Evidenced sightseeing walk",
        "plain_transfer": "Plain transfer",
        "opening_unverified": "Opening hours not officially verified",
        "map_no_coordinates": "This day has no stop coordinates yet.",
        "unscheduled_choices": "Selected but not scheduled",
        "capability_gaps": "Evidence still missing",
        "downloads": "Offline snapshots",
        "poster": "Day poster (PNG)",
        "pdf": "Trip PDF",
        "excel": "Excel workbook",
        "checklist": "Trip readiness checklist",
        "checklist_pending": "The readiness checklist is not generated yet.",
        "sources": "Evidence and sources",
        "no_sources": "No governed fact reached this plan.",
        "no_costs": "No cost evidence is available yet.",
        "fallback": "Fallback for this half-day",
        "fallback_trigger": "Trigger",
        "day_reoptimized": "day re-optimized",
        "hotel_anchor": "Hotel area",
        "morning": "Morning",
        "afternoon": "Afternoon",
        "checklist_help": "Generated from your trip, fully editable. Warnings never block the itinerary or its exports.",
        "checklist_needs_setup": "Save the trip setup first; the board is generated from it.",
        "calendar": "Readiness calendar (.ics)",
        "today_tasks": "Needed today",
        "checklist_preview": "Proposed checklist changes",
        "checklist_applied": "Checklist updated:",
        "checklist_current": "The board matches the current trip.",
        "apply_checklist": "Apply these changes",
        "will_be_dismissed": "will move to history",
        "open_tasks": "open tasks",
        "overdue": "Overdue",
        "due_soon": "Due soon",
        "due": "due",
        "timing": "Timing",
        "requirement_level": "Requirement",
        "required": "Required",
        "recommended": "Recommended",
        "optional": "Optional",
        "do_now": "Do now / before booking",
        "30_days_before": "30 days before",
        "7_days_before": "7 days before",
        "24_hours_before": "24 hours before",
        "departure_arrival_day": "Departure / arrival day",
        "progress": "Progress",
        "progress_to_do": "To do",
        "progress_waiting": "Waiting",
        "progress_done": "Done",
        "progress_not_applicable": "Not applicable",
        "not_applicable_reason": "Why is it not applicable?",
        "evidence": "Official evidence",
        "evidence_verified": "Verified",
        "evidence_verification_needed": "Verification needed",
        "evidence_verification_needed_help": "No official source recorded yet. This app never guesses an entry rule.",
        "expected_authority": "Confirm with",
        "source_url": "Official source URL",
        "authority_type": "Authority",
        "record_evidence": "Record this source",
        "evidence_recorded": "Official source recorded.",
        "last_checked": "Last checked",
        "save_task": "Save",
        "task_saved": "Task updated.",
        "dismiss_task": "Dismiss",
        "task_dismissed": "Moved to history.",
        "dismissed_history": "Dismissed history",
        "restore_task": "Restore",
        "task_restored": "Task restored.",
        "add_task": "Add a task",
        "task_title": "Task",
        "task_added": "Task added.",
        "entry_requirements": "Entry requirements",
        "immigration_customs": "Immigration and customs",
        "money": "Money",
        "connectivity": "Connectivity",
        "insurance_health": "Insurance and health",
        "transport_setup": "Transport setup",
        "reservations": "Reservations",
        "registrations": "Registrations",
        "packing": "Packing",
        "local_rules": "Local rules",
        "emergency": "Emergency",
        "government": "Government",
        "embassy": "Embassy",
        "immigration": "Immigration",
        "customs": "Customs",
        "health_authority": "Health authority",
        "transport_operator": "Transport operator",
        "attraction_operator": "Attraction operator",
        "task_entry_requirements": "Verify entry requirements for {destination}",
        "why_entry_requirements": "Denied boarding or refused entry",
        "task_passport_validity": "Confirm every passport stays valid for the whole trip",
        "why_passport_validity": "Denied boarding",
        "task_immigration_forms": "Check whether {destination} requires an arrival or customs declaration",
        "why_immigration_forms": "Held at the border or fined",
        "task_insurance_health": "Decide travel insurance and check health requirements",
        "why_insurance_health": "Unfunded medical cost, or a refused entry where cover is mandatory",
        "task_money": "Prepare payment methods and local cash",
        "why_money": "Unable to pay where cards are not accepted",
        "task_connectivity": "Arrange data connectivity",
        "why_connectivity": "No maps, tickets, or translation on arrival",
        "task_transport_setup": "Set up local transport payment or passes",
        "why_transport_setup": "Queues and higher fares on the first day",
        "task_local_rules": "Read local rules and etiquette that carry penalties",
        "why_local_rules": "Fines or refused access",
        "task_packing": "Pack against the planned weather and walking load",
        "why_packing": "Avoidable discomfort or an unusable item",
        "task_emergency": "Save emergency contacts and embassy details offline",
        "why_emergency": "No usable contact during an incident",
        "task_departure_recheck": "Recheck departure time, terminal, and any closures",
        "why_departure_recheck": "Missed departure",
        "task_accommodation_base": "Confirm accommodation and record its address offline",
        "why_accommodation_base": "No usable base for routing or for an arrival form",
        "task_place_booking": "Check opening hours and advance booking for {place}",
        "why_place_booking_timed": "A timed or limited entry sells out or closes the visit",
        "why_place_booking_open": "Queueing, or arriving when the place cannot be entered",
        "costs": "Costs",
        "costs_help": "Thai baht is the reporting currency; every expense keeps its original amount and currency. Rates are yours to set and buffer.",
        "rate_snapshot": "Exchange-rate snapshot",
        "rate_as_of": "Rate date",
        "rate_source": "Rate source",
        "rate_currency": "Currency",
        "rate_value": "THB per unit",
        "rate_buffer": "Buffer %",
        "save_rates": "Save rate snapshot",
        "rates_saved": "Rate snapshot saved.",
        "no_rates": "No rate snapshot yet; costs in other currencies stay unconverted.",
        "add_cost": "Add a cost",
        "cost_label": "What is it",
        "cost_amount": "Original amount",
        "cost_currency": "Original currency",
        "cost_state": "Payment state",
        "cost_actual": "Actual THB charged",
        "cost_payer": "Payer",
        "cost_share": "Share",
        "cost_added": "Cost saved.",
        "cost_removed": "Cost removed.",
        "remove_cost": "Remove",
        "estimate": "Estimate",
        "committed": "Committed",
        "paid": "Paid",
        "estimated_thb": "Estimated THB",
        "paid_thb": "Paid THB",
        "total_thb": "Total THB",
        "rate_missing": "No rate for this currency",
        "locked_charge": "Locked actual charge",
        "transport": "Transport",
        "accommodation_cost": "Accommodation",
        "activity": "Activity",
        "food": "Food",
        "fees": "Fees",
        "shopping_cost": "Shopping",
        "other": "Other",
        "routes": "Walking routes",
        "routes_help": "OpenRouteService foot routes between your selected places. Free tier, still counted in the ledger.",
        "fetch_routes": "Fetch walking routes",
        "routes_fetched": "Routes updated.",
        "routes_available": "Routes stored",
        "routes_needed": "Legs needed",
        "routes_skipped": "Skipped over the request cap",
        "routes_failed": "Legs the provider could not return",
        "no_routes": "No verified routes yet. The optimizer cannot confirm travel time without them.",
        "routes_need_places": "Choose at least two places with coordinates first.",
        "paid_usage": "Paid provider usage this month",
        "paid_requests": "requests",
        "paid_cap": "cap",
        "paid_stopped": "The monthly paid cap is reached; new paid calls are stopped until you raise it.",
        "paid_warning": "Paid spend has passed the warning line.",
        "raise_cap": "Raise the monthly cap (USD)",
        "save_cap": "Save cap",
        "cap_saved": "Monthly cap updated.",
        "timezone_evidence": "Destination time zone",
        "fetch_timezone": "Look up the time zone",
        "timezone_fetched": "Time zone recorded.",
        "no_timezone": "The destination time zone is not verified yet.",
        "timezone_cost": "One paid lookup, about US$0.005, cached for 180 days.",
        "opening_hours": "Opening hours",
        "fetch_hours": "Fetch opening hours",
        "hours_fetched": "Opening hours recorded.",
        "hours_usable": "Places with a verified window",
        "hours_cost": "One paid lookup per selected place, about US$0.025 each, cached for 3 days.",
        "hours_unusable": "Places with no usable window",
        "revision": "Revise the plan",
        "revision_help": "Quick actions change constraints, then the optimizer rebuilds the plan. Nothing is applied until you press Apply.",
        "revision_needs_plan": "Activate a plan before revising it.",
        "quick_action": "Quick action",
        "run_action": "Preview this change",
        "pending_revision": "Pending revision",
        "revision_assumptions": "Assumptions",
        "apply_revision": "Apply",
        "cancel_revision": "Cancel",
        "revision_applied": "Revision applied.",
        "revision_discarded": "Pending revision discarded.",
        "revision_blocked": "This revision cannot be applied yet: the rebuilt plan does not pass validation.",
        "changed_days": "Changed days",
        "no_changes": "No scheduled item changed.",
        "before": "before",
        "after": "after",
        "delta": "change",
        "moved_items": "Moved",
        "added_items": "Added",
        "removed_items": "Removed",
        "shortened_items": "Shortened",
        "lengthened_items": "Lengthened",
        "displaced_items": "No longer fits",
        "new_warnings": "New warnings",
        "cleared_warnings": "Warnings cleared",
        "revision_history": "Revision history",
        "restore_version": "Restore this version",
        "version_restored": "Earlier plan restored as a new version.",
        "op_explain": "Explain why",
        "op_fully_reoptimize": "Fully re-optimize",
        "op_reduce_walking": "Reduce walking",
        "op_reduce_daily_load": "Make the day easier",
        "op_fix_meal_timing": "Fix meal timing",
        "op_adjust_duration": "Adjust visit length",
        "op_lock_item": "Lock",
        "op_unlock_item": "Unlock",
        "op_drop_place": "Drop this place",
        "deterministic_reasons": "Deterministic reasons",
        "free_text": "Describe the change",
        "free_text_help": "One AI call turns your words into one supported change, then the optimizer rebuilds the plan. The model never sets an opening time, route, fare or closure.",
        "interpret": "Interpret this request",
        "ai_enabled": "Use AI to interpret free text",
        "ai_disabled_note": "AI is off. Quick actions, the optimizer, exports and everything else keep working.",
        "ai_cost": "About US$0.002 per interpretation, from the same monthly cap.",
        "interpreted_as": "Interpreted as",
        "clarification": "The assistant asks",
        "unsupported_request": "This request is not supported",
        "ai_missing_credentials": "No OpenAI key is configured, so free text cannot be interpreted. Quick actions still work.",
        "ai_offline": "The interpretation service could not be reached. Try again, or use a quick action.",
        "ai_refused": "The model declined this request. Rephrase it, or use a quick action.",
        "ai_invalid_reply": "The interpretation came back unusable, so nothing was changed.",
        "ai_rate_limited": "The interpretation service is rate limited. Try again shortly.",
        "ai_api_error": "The interpretation service returned an error, so nothing was changed.",
        "ai_disclosure": "Requests are sent without storage on the provider side; standard abuse-monitoring retention may still apply. Only the plan slice and your request are sent.",
        "journey": "Trip progress",
        "journey_needs_trip": "Create a trip to begin.",
        "journey_blocked": "Finish this first:",
        "stage_setup": "Trip and setup",
        "stage_places": "Places",
        "stage_evidence": "Evidence",
        "stage_optimize": "Build the plan",
        "stage_itinerary": "Itinerary",
        "stage_readiness": "Readiness",
        "stage_costs": "Costs",
        "stage_revise": "Revise",
        "section_build": "Build the trip",
        "section_use": "Use the trip",
    },
    "th": {
        "title": "ตัวช่วยวางแผนท่องเที่ยวส่วนตัว",
        "caption": "POC บนเครื่อง · ข้อมูลทริปแบบมีโครงสร้างอยู่ในคอมพิวเตอร์นี้",
        "new_trip": "เริ่มสร้างทริป",
        "trip_name": "ชื่อทริป (ไม่บังคับ)",
        "destination": "จุดหมายปลายทาง",
        "mode": "รูปแบบการวางแผน",
        "explore_first": "เลือกสถานที่ก่อน",
        "ready_to_schedule": "พร้อมจัดตาราง",
        "create": "สร้างทริป",
        "created": "บันทึกทริปแล้ว",
        "destination_required": "กรุณาระบุจุดหมายปลายทาง",
        "saved_trips": "ทริปที่บันทึกไว้",
        "resume": "เปิดทริปต่อ",
        "status": "สถานะ",
        "draft": "แบบร่าง",
        "mode_label": "โหมด",
        "active_plan": "เวอร์ชันแผนที่ใช้งาน",
        "no_plan": "ยังไม่ได้สร้างตาราง หน้านี้ใช้ตั้งค่าและค้นหาสถานที่เท่านั้น",
        "empty": "สร้างทริปแรกเพื่อเริ่มต้น",
        "setup": "ตั้งค่าทริป",
        "setup_help": "บันทึกร่างได้ทุกเมื่อ และยืนยันก่อนให้แอปเรียกค้นหาสถานที่",
        "trip_basics": "1 · ข้อมูลทริป",
        "dates_known": "ทราบวันเดินทางแล้ว",
        "start_date": "วันเริ่มต้น",
        "end_date": "วันสิ้นสุด",
        "arrival_known": "ทราบเวลาถึงโดยประมาณ",
        "arrival_time": "เวลาถึง",
        "departure_known": "ทราบเวลาออกโดยประมาณ",
        "departure_time": "เวลาออก",
        "accommodation": "ที่พัก",
        "owner_style": "2 · สไตล์หลักของเจ้าของทริป",
        "owner_age": "อายุเจ้าของทริป (0 = ยังไม่ระบุ)",
        "main_style": "สไตล์หลัก · เลือกอย่างน้อยหนึ่งข้อ",
        "also_enjoy": "ชอบเพิ่มเติม",
        "avoid": "อยากหลีกเลี่ยง",
        "comfort": "ความสบายที่ต้องการ",
        "description": "รายละเอียดหรือบริบทเพิ่มเติม (ไม่บังคับ)",
        "travellers": "3 · ผู้ร่วมทริป",
        "member_count": "จำนวนผู้ร่วมทริปเพิ่มเติม",
        "member": "ผู้ร่วมทริป",
        "member_name": "ชื่อเล่น / ป้ายชื่อ",
        "member_age": "อายุ (0 = ยังไม่ระบุ)",
        "member_tags": "แท็กความชอบ (ไม่บังคับ)",
        "member_notes": "หมายเหตุ (ไม่บังคับ)",
        "member_must": "ข้อจำเป็นที่ต้องทำตาม · หนึ่งข้อต่อบรรทัด",
        "requirements": "4 · ข้อจำเป็นที่ต้องทำตาม",
        "owner_must": "ใส่เฉพาะสิ่งที่ต่อรองไม่ได้ · หนึ่งข้อต่อบรรทัด (ไม่บังคับ)",
        "save_draft": "บันทึกร่าง",
        "confirm": "ยืนยันการตั้งค่า",
        "draft_saved": "บันทึกร่างไว้ในเครื่องแล้ว โดยไม่ได้เรียกผู้ให้บริการ",
        "confirmed": "ยืนยันการตั้งค่าแล้ว พร้อมค้นหาสถานที่",
        "main_required": "เลือกสไตล์หลักอย่างน้อยหนึ่งข้อก่อนยืนยัน",
        "review": "5 · ตรวจสอบ",
        "setup_state": "สถานะการตั้งค่า",
        "draft_setup": "ร่างการตั้งค่า",
        "confirmed_setup": "ยืนยันเพื่อค้นหาแล้ว",
        "people": "จำนวนคน",
        "preferences": "แท็กเจ้าของทริป",
        "no_dates": "วันเดินทางยังไม่บังคับ ผลลัพธ์จึงยังไม่ใช่ตารางตามวันที่",
        "discover_title": "ค้นหาสถานที่แบบกว้าง",
        "discover_help": "ทำงานเมื่อกดเท่านั้น ใช้ฐาน OpenStreetMap ทั่วโลกแบบจำกัดพื้นที่และแคช 7 วัน ผลลัพธ์ครอบคลุมกว้างแต่ไม่ครบทุกแห่ง",
        "discover": "ค้นหาสถานที่",
        "refresh": "รีเฟรชข้อมูลผู้ให้บริการ",
        "discovering": "กำลังรวบรวมสถานที่พื้นฐาน…",
        "discovery_saved": "บันทึกผลการค้นหาแล้ว",
        "coverage": "รายงานความครอบคลุม",
        "provider_status": "สถานะผู้ให้บริการ",
        "provider_verified": "ยืนยันแล้ว",
        "provider_stale": "ข้อมูลเก่า",
        "provider_unavailable": "ใช้งานไม่ได้",
        "provider_error": "เกิดข้อผิดพลาด",
        "candidates": "สถานที่",
        "duplicates": "รายการซ้ำที่รวมแล้ว",
        "cells": "พื้นที่ที่พบสถานที่",
        "unranked": "เป็นรายการพื้นฐานเท่านั้น ยังไม่ได้จัดอันดับหรือกรองด้วยความชอบ",
        "stale_setup": "ผลนี้มาจากการตั้งค่าเก่า ยังดูได้ แต่ควรยืนยันและค้นหาใหม่ก่อนจัดอันดับ",
        "provider_gap": "ผู้ให้บริการยังส่งรายการปัจจุบันไม่ได้ การตั้งค่าของคุณยังปลอดภัย และช่องว่างของข้อมูลแสดงด้านล่าง",
        "no_candidates": "ไม่พบสถานที่ที่ใช้ได้ โปรดดูช่องว่างของข้อมูลและลองใหม่ภายหลัง",
        "name": "ชื่อ",
        "local_name": "ชื่อท้องถิ่น",
        "category": "ประเภท",
        "opening": "หลักฐานเวลาเปิด",
        "source": "แหล่งข้อมูล",
        "details": "รายละเอียดความครอบคลุมแบบมาตรฐาน",
        "osm_notice": "บริการสาธารณะ OpenStreetMap ใช้แบบส่วนตัว ปริมาณต่ำ และผู้ใช้กดเอง แอประบุตัวตน แคชคำขอซ้ำ และไม่ทำ autocomplete",
        "ranking_title": "การ์ดสถานที่ที่เหมาะกับทริป",
        "ranking_help": "คะแนนใช้เรียงการ์ด ไม่ใช่การรับประกัน ข้อมูลเส้นทาง คนแน่น เรตติ้ง เวลาเปิดวันหยุด และช่วงเวลาที่ดีที่สุดที่ยังขาดจะแสดงอย่างชัดเจนและให้คะแนนแบบกลาง",
        "ranking_wait": "ยืนยันการตั้งค่าปัจจุบันและค้นหาสถานที่ก่อนจัดอันดับ",
        "lane": "กลุ่มการ์ด",
        "main_queue": "เหมาะกับทริปของคุณ",
        "city_icons": "แลนด์มาร์กสำคัญ",
        "worth_it_if": "คุ้มถ้า…",
        "local_alternatives": "ตัวเลือกท้องถิ่น",
        "browse_all": "ดูทั้งหมด",
        "select_card": "เลือกการ์ด",
        "no_lane_cards": "ยังไม่มีการ์ดที่เข้าเงื่อนไขกลุ่มนี้",
        "score": "คะแนน",
        "duration": "เวลาชมโดยประมาณ",
        "minutes": "นาที",
        "planner_estimate": "ค่าประมาณตามประเภทจากตัววางแผน ยังไม่ยืนยันโดยสถานที่",
        "feasibility": "ความเป็นไปได้",
        "not_evaluated": "ยังไม่ประเมินจนกว่าจะจัดแผน",
        "why": "เหตุผลที่แสดง",
        "pros": "ข้อดี",
        "cons": "ข้อเสีย / ข้อมูลที่ยังขาด",
        "card_detail": "เหตุผลที่แสดง ข้อดี และช่องว่างข้อมูล",
        "breakdown": "รายละเอียดคะแนน 30/20/20/10/15/5",
        "dimension": "องค์ประกอบ",
        "points": "คะแนน",
        "maximum": "คะแนนเต็ม",
        "deductions": "คะแนนหักพร้อมเหตุผล",
        "no_deductions": "ไม่มีคะแนนหักที่มีหลักฐานรองรับ",
        "matched_tags": "แท็กที่ตรงกัน",
        "group_weights": "น้ำหนักสมาชิกและสัญญาณที่เรียนรู้",
        "choice": "ตัวเลือกของคุณ",
        "must_do": "ต้องไป",
        "interested": "สนใจ",
        "maybe": "อาจจะ",
        "not_for_trip": "ไม่เหมาะกับทริปนี้",
        "rejection_reason": "เหตุผลเพิ่มเติมสำหรับไม่เหมาะกับทริปนี้",
        "no_reason": "ไม่ระบุเหตุผล",
        "choice_saved": "บันทึกแล้ว การ์ดที่ยังไม่เลือกถูกเรียงใหม่ และรายการดูทั้งหมดยังเก็บทุกสถานที่",
        "current_choice": "ตัวเลือกปัจจุบัน",
        "clear_choice": "ล้างตัวเลือก",
        "choice_cleared": "ล้างตัวเลือกแล้ว",
        "exploration_card": "การ์ดสำรวจที่ระบบกันไว้",
        "icon_card": "มีหลักฐานว่าเป็นแลนด์มาร์กเด่น",
        "source_rating": "เรตติ้งจากแหล่งข้อมูล",
        "not_enriched": "ยังไม่ได้เพิ่มข้อมูล",
        "route_effort": "เส้นทาง / การเดิน",
        "not_routed": "ยังไม่ได้คำนวณเส้นทาง",
        "browse_notice": "สถานที่มาตรฐานปัจจุบันทุกแห่งอยู่ที่นี่ รวมทั้งที่เลือกแล้วและคะแนนต่ำ",
        "reconciliation": "ตรวจสอบสถานที่ที่เลือกทั้งหมด",
        "reconciliation_help": "ไม่มีสถานที่ที่เลือกหายไป ตัวเลือกจากการ์ดยังคงรอจนกว่าจะรันระบบจัดแผนทั้งทริปด้านล่าง",
        "no_selected": "ยังไม่มีสถานที่ที่เลือกเป็น ต้องไป หรือ สนใจ",
        "pending_optimizer": "รอจัดแผน",
        "present_latest": "อยู่ในการค้นหาล่าสุด",
        "next_step": "ขั้นต่อไป",
        "run_optimizer": "รันระบบจัดแผนทั้งทริปด้านล่าง",
        "all_choices": "ตัวเลือกที่บันทึกทั้งหมด",
        "formula_note": "คะแนนกลางหมายถึงข้อมูลยังขาด ไม่ได้แปลว่าสถานที่นั้นอยู่ระดับกลางจริง",
        "photo_source": "รูปจากแหล่งข้อมูลเปิด",
        "photo_unavailable": "ยังไม่มีแหล่งรูปที่อนุญาตให้ใช้",
        "optimizer_title": "ระบบจัดแผนทั้งทริป",
        "optimizer_help": "ใช้สถานที่ที่เลือกทั้งหมดข้ามทุกวันและสลับวันหรือลำดับได้ แต่จะไม่เดาเส้นทาง เวลาเปิด ทางเข้า หรือรายการล็อก",
        "generate_plan": "สร้าง / รีเฟรชแผน 3 แบบ",
        "optimizing": "กำลังจัดแผนทั้งทริป…",
        "preview_saved": "บันทึกตัวอย่างแผนไว้ในเครื่องแล้ว",
        "choose_before_plan": "เลือกอย่างน้อยหนึ่งสถานที่เป็น ต้องไป สนใจ หรือ อาจจะ ก่อน",
        "stay_recommendation": "ยังไม่กำหนดวันแน่นอน — เปรียบเทียบจำนวนวันที่แนะนำ",
        "stay_option": "รูปแบบระยะเวลา",
        "days": "วัน",
        "daily_capacity": "เวลาวางแผนต่อวัน",
        "variant": "รูปแบบแผน",
        "best_balance": "สมดุลที่สุด",
        "relaxed": "สบายขึ้น",
        "more_highlights": "เก็บไฮไลต์มากขึ้น",
        "ready": "พร้อมใช้",
        "provisional": "ชั่วคราว / ต้องยอมรับผลกระทบ",
        "unavailable": "ยังสร้างไม่ได้",
        "scheduled_visits": "สถานที่",
        "travel_minutes": "เวลาเดินทาง",
        "walking_minutes": "เวลาเดิน",
        "plain_walking_minutes": "การเดินทางธรรมดา",
        "buffer_minutes": "เวลาสำรอง",
        "optimizer_warning": "คำเตือนและข้อมูลที่ยังขาด",
        "optimizer_reconciliation": "ผลตรวจสถานที่ที่เลือกทั้งหมด",
        "fits": "ใส่ในแผนได้",
        "fits_with_tradeoff": "ใส่ได้เมื่อยอมรับข้อแลกเปลี่ยน",
        "cannot_currently_fit": "ตอนนี้ใส่ในแผนไม่ได้",
        "reason": "เหตุผล",
        "consequence": "ผลกระทบ / ขั้นต่อไปที่เล็กที่สุด",
        "timeline": "ตารางเวลาที่ตรวจแล้ว",
        "item_type": "ประเภท",
        "start": "เริ่ม",
        "end": "จบ",
        "place_or_leg": "สถานที่ / ช่วงเดินทาง",
        "activate_plan": "ใช้เป็นแผนปัจจุบัน",
        "plan_activated": "เปิดใช้แผนที่ผ่านการตรวจแล้ว",
        "activation_disabled": "เปิดใช้ได้เฉพาะแผนสถานะ พร้อมใช้ และผ่านการตรวจครบ",
        "no_schedule": "ยังจัดสถานที่ที่เลือกอย่างปลอดภัยไม่ได้ด้วยข้อมูลปัจจุบัน",
        "greedy_check": "ผลทั้งทริปเท่ากับหรือดีกว่าแผนแบบจัดทีละวัน",
        "optimizer_limit": "ระบบหยุดเมื่อถึงขีดจำกัดและแสดงเฉพาะผลที่ตรวจแล้ว",
        "use_title": "แผนที่ใช้งาน",
        "use_help": "หน้านี้อ่านสแนปช็อตส่งออกชุดเดียว โพสเตอร์ PDF และ Excel จะอ่านตัวเลขชุดเดียวกัน",
        "no_active_plan": "ยังไม่มีแผนที่ใช้งาน กรุณาเปิดใช้แผนที่ผ่านการตรวจด้านบน",
        "superseded_plan": "นี่คือแผนเวอร์ชันเก่า แผนที่ใช้งานเปลี่ยนไปแล้ว",
        "exported_at": "สร้างสแนปช็อตเมื่อ",
        "readiness": "ความพร้อม",
        "action_needed": "ต้องดำเนินการ",
        "verification_needed": "ต้องตรวจสอบหลักฐาน",
        "state_confirmed": "✅ ยืนยันแล้ว",
        "state_recheck": "🕒 ต้องตรวจซ้ำ",
        "state_tradeoff_accepted": "⚖️ ยอมรับผลกระทบแล้ว",
        "state_unverified_conflict": "⚠️ ยังไม่ยืนยัน / ข้อมูลขัดแย้ง",
        "state_locked": "🔒 ล็อกไว้",
        "highest_risk": "ความเสี่ยงสูงสุดของวันนี้",
        "tab_map": "แผนที่",
        "visit_minutes": "เวลาอยู่ในสถานที่",
        "rewarding_walking_minutes": "การเดินที่คุ้มค่า",
        "stop": "จุดที่",
        "travel_mode": "รูปแบบเดินทาง",
        "walk_portion": "ช่วงที่ต้องเดิน",
        "distance": "ระยะทาง",
        "transfers": "จำนวนต่อรถ",
        "boarding_buffer": "เวลาสำรองก่อนขึ้นรถ",
        "sightseeing_walk": "เส้นทางเดินชมเมืองที่มีหลักฐาน",
        "plain_transfer": "การเดินทางธรรมดา",
        "opening_unverified": "เวลาเปิดยังไม่ได้ยืนยันจากแหล่งทางการ",
        "map_no_coordinates": "วันนี้ยังไม่มีพิกัดของจุดหมาย",
        "unscheduled_choices": "เลือกไว้แต่ยังจัดลงตารางไม่ได้",
        "capability_gaps": "หลักฐานที่ยังขาด",
        "downloads": "ไฟล์สำหรับใช้ออฟไลน์",
        "poster": "โพสเตอร์รายวัน (PNG)",
        "pdf": "PDF ทั้งทริป",
        "excel": "ไฟล์ Excel",
        "checklist": "รายการเตรียมตัวก่อนเดินทาง",
        "checklist_pending": "ยังไม่ได้สร้างรายการเตรียมตัว",
        "sources": "หลักฐานและแหล่งข้อมูล",
        "no_sources": "ยังไม่มีข้อมูลที่ตรวจสอบแล้วเข้าสู่แผนนี้",
        "no_costs": "ยังไม่มีข้อมูลค่าใช้จ่าย",
        "fallback": "แผนสำรองของช่วงนี้",
        "fallback_trigger": "เงื่อนไขที่ทำให้ใช้แผนสำรอง",
        "day_reoptimized": "จัดตารางวันนี้ใหม่แล้ว",
        "hotel_anchor": "ย่านที่พัก",
        "morning": "ช่วงเช้า",
        "afternoon": "ช่วงบ่าย",
        "checklist_help": "สร้างจากข้อมูลทริปและแก้ไขได้ทั้งหมด คำเตือนไม่ปิดกั้นตารางเดินทางหรือไฟล์ส่งออก",
        "checklist_needs_setup": "บันทึกการตั้งค่าทริปก่อน ระบบจะสร้างรายการจากข้อมูลนั้น",
        "calendar": "ปฏิทินเตรียมตัว (.ics)",
        "today_tasks": "ต้องทำวันนี้",
        "checklist_preview": "การเปลี่ยนแปลงที่เสนอ",
        "checklist_applied": "อัปเดตรายการแล้ว:",
        "checklist_current": "รายการตรงกับข้อมูลทริปปัจจุบันแล้ว",
        "apply_checklist": "ใช้การเปลี่ยนแปลงนี้",
        "will_be_dismissed": "จะย้ายไปประวัติ",
        "open_tasks": "รายการที่ยังไม่เสร็จ",
        "overdue": "เกินกำหนด",
        "due_soon": "ใกล้ครบกำหนด",
        "due": "กำหนด",
        "timing": "ช่วงเวลา",
        "requirement_level": "ระดับความจำเป็น",
        "required": "จำเป็น",
        "recommended": "แนะนำ",
        "optional": "ไม่บังคับ",
        "do_now": "ทำทันที / ก่อนจอง",
        "30_days_before": "ก่อนเดินทาง 30 วัน",
        "7_days_before": "ก่อนเดินทาง 7 วัน",
        "24_hours_before": "ก่อนเดินทาง 24 ชั่วโมง",
        "departure_arrival_day": "วันเดินทาง / วันถึง",
        "progress": "สถานะงาน",
        "progress_to_do": "ยังไม่ทำ",
        "progress_waiting": "รอผล",
        "progress_done": "เสร็จแล้ว",
        "progress_not_applicable": "ไม่เกี่ยวข้อง",
        "not_applicable_reason": "เหตุผลที่ไม่เกี่ยวข้อง",
        "evidence": "หลักฐานจากแหล่งทางการ",
        "evidence_verified": "ยืนยันแล้ว",
        "evidence_verification_needed": "ต้องตรวจสอบ",
        "evidence_verification_needed_help": "ยังไม่มีแหล่งทางการบันทึกไว้ แอปนี้ไม่เดากฎการเข้าเมือง",
        "expected_authority": "ตรวจสอบกับ",
        "source_url": "ลิงก์แหล่งทางการ",
        "authority_type": "หน่วยงาน",
        "record_evidence": "บันทึกแหล่งข้อมูลนี้",
        "evidence_recorded": "บันทึกแหล่งทางการแล้ว",
        "last_checked": "ตรวจครั้งล่าสุด",
        "save_task": "บันทึก",
        "task_saved": "อัปเดตรายการแล้ว",
        "dismiss_task": "ซ่อนรายการ",
        "task_dismissed": "ย้ายไปประวัติแล้ว",
        "dismissed_history": "ประวัติรายการที่ซ่อน",
        "restore_task": "นำกลับมา",
        "task_restored": "นำรายการกลับมาแล้ว",
        "add_task": "เพิ่มรายการ",
        "task_title": "ชื่อรายการ",
        "task_added": "เพิ่มรายการแล้ว",
        "entry_requirements": "ข้อกำหนดการเข้าประเทศ",
        "immigration_customs": "ตรวจคนเข้าเมืองและศุลกากร",
        "money": "การเงิน",
        "connectivity": "อินเทอร์เน็ต",
        "insurance_health": "ประกันและสุขภาพ",
        "transport_setup": "การเดินทางในพื้นที่",
        "reservations": "การจอง",
        "registrations": "การลงทะเบียน",
        "packing": "การจัดกระเป๋า",
        "local_rules": "กฎท้องถิ่น",
        "emergency": "เหตุฉุกเฉิน",
        "government": "หน่วยงานรัฐ",
        "embassy": "สถานทูต",
        "immigration": "ตรวจคนเข้าเมือง",
        "customs": "ศุลกากร",
        "health_authority": "หน่วยงานสาธารณสุข",
        "transport_operator": "ผู้ให้บริการขนส่ง",
        "attraction_operator": "ผู้ดูแลสถานที่",
        "task_entry_requirements": "ตรวจสอบข้อกำหนดการเข้า {destination} จากแหล่งทางการ",
        "why_entry_requirements": "ถูกปฏิเสธการขึ้นเครื่องหรือปฏิเสธการเข้าประเทศ",
        "task_passport_validity": "ยืนยันว่าหนังสือเดินทางทุกเล่มมีอายุครอบคลุมทั้งทริป",
        "why_passport_validity": "ถูกปฏิเสธการขึ้นเครื่อง",
        "task_immigration_forms": "ตรวจว่า {destination} ต้องกรอกแบบฟอร์มขาเข้าหรือใบสำแดงศุลกากรหรือไม่",
        "why_immigration_forms": "ถูกกักที่ด่านตรวจหรือถูกปรับ",
        "task_insurance_health": "ตัดสินใจเรื่องประกันการเดินทางและตรวจข้อกำหนดด้านสุขภาพ",
        "why_insurance_health": "ค่ารักษาที่ไม่มีผู้รับผิดชอบ หรือถูกปฏิเสธเข้าประเทศหากบังคับให้มีประกัน",
        "task_money": "เตรียมวิธีชำระเงินและเงินสดสกุลท้องถิ่น",
        "why_money": "จ่ายเงินไม่ได้ในที่ที่ไม่รับบัตร",
        "task_connectivity": "จัดเตรียมอินเทอร์เน็ตสำหรับใช้ระหว่างเดินทาง",
        "why_connectivity": "ใช้แผนที่ ตั๋ว หรือการแปลภาษาไม่ได้เมื่อไปถึง",
        "task_transport_setup": "ตั้งค่าการชำระเงินหรือบัตรโดยสารขนส่งท้องถิ่น",
        "why_transport_setup": "ต้องต่อคิวและจ่ายค่าโดยสารแพงขึ้นในวันแรก",
        "task_local_rules": "อ่านกฎและธรรมเนียมท้องถิ่นที่มีบทลงโทษ",
        "why_local_rules": "ถูกปรับหรือถูกปฏิเสธไม่ให้เข้า",
        "task_packing": "จัดกระเป๋าให้เหมาะกับสภาพอากาศและปริมาณการเดินที่วางแผนไว้",
        "why_packing": "ไม่สบายตัวโดยไม่จำเป็น หรือของที่พกไปใช้ไม่ได้",
        "task_emergency": "บันทึกเบอร์ฉุกเฉินและข้อมูลสถานทูตให้ใช้ได้แบบออฟไลน์",
        "why_emergency": "ติดต่อใครไม่ได้เมื่อเกิดเหตุ",
        "task_departure_recheck": "ตรวจเวลาออกเดินทาง อาคารผู้โดยสาร และการปิดให้บริการอีกครั้ง",
        "why_departure_recheck": "พลาดเที่ยวเดินทาง",
        "task_accommodation_base": "ยืนยันที่พักและบันทึกที่อยู่ให้ใช้ได้แบบออฟไลน์",
        "why_accommodation_base": "ไม่มีฐานที่พักสำหรับคำนวณเส้นทางหรือกรอกแบบฟอร์มขาเข้า",
        "task_place_booking": "ตรวจเวลาเปิดและการจองล่วงหน้าของ {place}",
        "why_place_booking_timed": "รอบเข้าชมแบบกำหนดเวลาหรือจำนวนจำกัดอาจเต็มหรือปิดรับ",
        "why_place_booking_open": "ต้องต่อคิว หรือไปถึงตอนที่เข้าชมไม่ได้",
        "costs": "ค่าใช้จ่าย",
        "costs_help": "รายงานเป็นเงินบาท และเก็บจำนวนเงินสกุลเดิมไว้ทุกรายการ อัตราแลกเปลี่ยนคุณกำหนดและเผื่อได้เอง",
        "rate_snapshot": "ชุดอัตราแลกเปลี่ยน",
        "rate_as_of": "วันที่ของอัตรา",
        "rate_source": "แหล่งอัตรา",
        "rate_currency": "สกุลเงิน",
        "rate_value": "บาทต่อหนึ่งหน่วย",
        "rate_buffer": "เผื่อ %",
        "save_rates": "บันทึกชุดอัตรา",
        "rates_saved": "บันทึกชุดอัตราแล้ว",
        "no_rates": "ยังไม่มีชุดอัตรา รายการสกุลอื่นจะยังไม่ถูกแปลงเป็นบาท",
        "add_cost": "เพิ่มค่าใช้จ่าย",
        "cost_label": "รายการ",
        "cost_amount": "จำนวนเงินสกุลเดิม",
        "cost_currency": "สกุลเงินเดิม",
        "cost_state": "สถานะการจ่าย",
        "cost_actual": "ยอดที่จ่ายจริง (บาท)",
        "cost_payer": "ผู้จ่าย",
        "cost_share": "การแบ่งจ่าย",
        "cost_added": "บันทึกค่าใช้จ่ายแล้ว",
        "cost_removed": "ลบค่าใช้จ่ายแล้ว",
        "remove_cost": "ลบ",
        "estimate": "ประมาณการ",
        "committed": "ผูกพันแล้ว",
        "paid": "จ่ายแล้ว",
        "estimated_thb": "ประมาณการ (บาท)",
        "paid_thb": "จ่ายแล้ว (บาท)",
        "total_thb": "รวม (บาท)",
        "rate_missing": "ไม่มีอัตราสำหรับสกุลนี้",
        "locked_charge": "ยอดจ่ายจริงถูกล็อกไว้",
        "transport": "การเดินทาง",
        "accommodation_cost": "ที่พัก",
        "activity": "กิจกรรม",
        "food": "อาหาร",
        "fees": "ค่าธรรมเนียม",
        "shopping_cost": "ช้อปปิ้ง",
        "other": "อื่นๆ",
        "routes": "เส้นทางเดิน",
        "routes_help": "เส้นทางเดินจาก OpenRouteService ระหว่างสถานที่ที่เลือก ใช้ฟรีแต่ยังนับในบัญชีการใช้งาน",
        "fetch_routes": "ดึงเส้นทางเดิน",
        "routes_fetched": "อัปเดตเส้นทางแล้ว",
        "routes_available": "เส้นทางที่เก็บไว้",
        "routes_needed": "ช่วงเดินทางที่ต้องมี",
        "routes_skipped": "ข้ามเพราะเกินโควตาการเรียก",
        "routes_failed": "ช่วงที่ผู้ให้บริการตอบไม่ได้",
        "no_routes": "ยังไม่มีเส้นทางที่ยืนยัน ระบบจัดแผนจึงยืนยันเวลาเดินทางไม่ได้",
        "routes_need_places": "เลือกสถานที่ที่มีพิกัดอย่างน้อยสองแห่งก่อน",
        "paid_usage": "การใช้บริการแบบมีค่าใช้จ่ายเดือนนี้",
        "paid_requests": "ครั้ง",
        "paid_cap": "เพดาน",
        "paid_stopped": "ถึงเพดานค่าใช้จ่ายรายเดือนแล้ว ระบบหยุดเรียกบริการแบบมีค่าใช้จ่ายจนกว่าจะเพิ่มเพดาน",
        "paid_warning": "ค่าใช้จ่ายเกินเส้นเตือนแล้ว",
        "raise_cap": "เพิ่มเพดานรายเดือน (USD)",
        "save_cap": "บันทึกเพดาน",
        "cap_saved": "อัปเดตเพดานแล้ว",
        "timezone_evidence": "เขตเวลาของปลายทาง",
        "fetch_timezone": "ตรวจเขตเวลา",
        "timezone_fetched": "บันทึกเขตเวลาแล้ว",
        "no_timezone": "ยังไม่ได้ยืนยันเขตเวลาของปลายทาง",
        "timezone_cost": "เรียกแบบมีค่าใช้จ่ายหนึ่งครั้ง ประมาณ 0.005 ดอลลาร์ เก็บไว้ 180 วัน",
        "opening_hours": "เวลาเปิดทำการ",
        "fetch_hours": "ดึงเวลาเปิดทำการ",
        "hours_fetched": "บันทึกเวลาเปิดทำการแล้ว",
        "hours_usable": "สถานที่ที่มีช่วงเวลายืนยันแล้ว",
        "hours_cost": "เรียกแบบมีค่าใช้จ่ายหนึ่งครั้งต่อสถานที่ ประมาณ 0.025 ดอลลาร์ เก็บไว้ 3 วัน",
        "hours_unusable": "สถานที่ที่ยังไม่มีช่วงเวลาที่ใช้ได้",
        "revision": "แก้ไขแผน",
        "revision_help": "คำสั่งด่วนปรับเงื่อนไข แล้วระบบจัดแผนสร้างตารางใหม่ ยังไม่มีอะไรถูกใช้จนกดยืนยัน",
        "revision_needs_plan": "เปิดใช้แผนก่อนจึงจะแก้ไขได้",
        "quick_action": "คำสั่งด่วน",
        "run_action": "ดูผลของการเปลี่ยนนี้",
        "pending_revision": "การแก้ไขที่รออยู่",
        "revision_assumptions": "ข้อสันนิษฐาน",
        "apply_revision": "ยืนยันใช้",
        "cancel_revision": "ยกเลิก",
        "revision_applied": "ใช้การแก้ไขแล้ว",
        "revision_discarded": "ยกเลิกการแก้ไขที่รออยู่แล้ว",
        "revision_blocked": "ยังใช้การแก้ไขนี้ไม่ได้ เพราะแผนที่สร้างใหม่ไม่ผ่านการตรวจ",
        "changed_days": "วันที่เปลี่ยน",
        "no_changes": "ไม่มีรายการในตารางเปลี่ยน",
        "before": "ก่อน",
        "after": "หลัง",
        "delta": "เปลี่ยนแปลง",
        "moved_items": "ย้าย",
        "added_items": "เพิ่ม",
        "removed_items": "เอาออก",
        "shortened_items": "ลดเวลา",
        "lengthened_items": "เพิ่มเวลา",
        "displaced_items": "จัดลงตารางไม่ได้แล้ว",
        "new_warnings": "คำเตือนใหม่",
        "cleared_warnings": "คำเตือนที่หมดไป",
        "revision_history": "ประวัติการแก้ไข",
        "restore_version": "ย้อนไปเวอร์ชันนี้",
        "version_restored": "ย้อนแผนเดิมเป็นเวอร์ชันใหม่แล้ว",
        "op_explain": "อธิบายเหตุผล",
        "op_fully_reoptimize": "จัดแผนใหม่ทั้งทริป",
        "op_reduce_walking": "ลดการเดิน",
        "op_reduce_daily_load": "ทำให้วันสบายขึ้น",
        "op_fix_meal_timing": "แก้เวลามื้ออาหาร",
        "op_adjust_duration": "ปรับเวลาชม",
        "op_lock_item": "ล็อก",
        "op_unlock_item": "ปลดล็อก",
        "op_drop_place": "เอาสถานที่นี้ออก",
        "deterministic_reasons": "เหตุผลจากการคำนวณ",
        "free_text": "อธิบายการเปลี่ยนที่ต้องการ",
        "free_text_help": "เรียก AI หนึ่งครั้งเพื่อแปลงข้อความเป็นการเปลี่ยนที่รองรับหนึ่งอย่าง แล้วระบบจัดแผนสร้างตารางใหม่ โมเดลไม่กำหนดเวลาเปิด เส้นทาง ค่าโดยสาร หรือการปิดให้บริการ",
        "interpret": "ตีความคำขอนี้",
        "ai_enabled": "ใช้ AI ตีความข้อความอิสระ",
        "ai_disabled_note": "ปิด AI อยู่ คำสั่งด่วน ระบบจัดแผน การส่งออก และส่วนอื่นยังใช้งานได้ปกติ",
        "ai_cost": "ประมาณ 0.002 ดอลลาร์ต่อการตีความ ใช้เพดานรายเดือนเดียวกัน",
        "interpreted_as": "ตีความเป็น",
        "clarification": "ผู้ช่วยขอความชัดเจน",
        "unsupported_request": "ยังไม่รองรับคำขอนี้",
        "ai_missing_credentials": "ยังไม่ได้ตั้งค่าคีย์ OpenAI จึงตีความข้อความอิสระไม่ได้ คำสั่งด่วนยังใช้ได้",
        "ai_offline": "ติดต่อบริการตีความไม่ได้ ลองอีกครั้งหรือใช้คำสั่งด่วน",
        "ai_refused": "โมเดลปฏิเสธคำขอนี้ ลองเรียบเรียงใหม่หรือใช้คำสั่งด่วน",
        "ai_invalid_reply": "ผลการตีความใช้ไม่ได้ จึงไม่มีการเปลี่ยนแปลง",
        "ai_rate_limited": "บริการตีความถูกจำกัดอัตราการเรียก ลองอีกครั้งในไม่ช้า",
        "ai_api_error": "บริการตีความแจ้งข้อผิดพลาด จึงไม่มีการเปลี่ยนแปลง",
        "ai_disclosure": "ส่งคำขอโดยไม่ให้ผู้ให้บริการจัดเก็บ แต่การเก็บเพื่อตรวจสอบการใช้งานผิดวัตถุประสงค์อาจยังมีผล ส่งเฉพาะข้อมูลแผนส่วนที่เกี่ยวข้องและคำขอของคุณ",
        "journey": "ความคืบหน้าของทริป",
        "journey_needs_trip": "สร้างทริปเพื่อเริ่มต้น",
        "journey_blocked": "ทำขั้นนี้ให้เสร็จก่อน:",
        "stage_setup": "ทริปและการตั้งค่า",
        "stage_places": "สถานที่",
        "stage_evidence": "หลักฐาน",
        "stage_optimize": "สร้างแผน",
        "stage_itinerary": "ตารางเดินทาง",
        "stage_readiness": "ความพร้อม",
        "stage_costs": "ค่าใช้จ่าย",
        "stage_revise": "แก้ไขแผน",
        "section_build": "สร้างทริป",
        "section_use": "ใช้งานทริป",
    },
}

TAG_TEXT = {
    "en": {
        "sightseeing": "Sightseeing",
        "culture": "Culture",
        "nature": "Nature",
        "activity": "Activity",
        "shopping": "Shopping",
        "chill": "Chill",
        "local_street_food": "Local street food",
        "photography": "Photography",
        "night_view": "Night view",
        "markets": "Markets",
        "architecture": "Architecture",
        "neighborhoods": "Neighbourhoods",
        "tourist_traps": "Tourist traps",
        "plain_long_walks": "Plain long walks",
        "late_meals": "Late meals",
        "heavy_crowds": "Heavy crowds",
        "balanced_pace": "Balanced pace",
        "rewarding_walks": "Rewarding walks",
        "meal_on_time": "Meals on time",
        "rest_breaks": "Rest breaks",
        "low_walking": "Low walking",
    },
    "th": {
        "sightseeing": "เที่ยวชมเมือง",
        "culture": "วัฒนธรรม",
        "nature": "ธรรมชาติ",
        "activity": "กิจกรรม",
        "shopping": "ช้อปปิ้ง",
        "chill": "สบาย ๆ",
        "local_street_food": "อาหารข้างทางท้องถิ่น",
        "photography": "ถ่ายภาพ",
        "night_view": "วิวกลางคืน",
        "markets": "ตลาด",
        "architecture": "สถาปัตยกรรม",
        "neighborhoods": "ย่านน่าเดิน",
        "tourist_traps": "แหล่งดักนักท่องเที่ยว",
        "plain_long_walks": "เดินไกลแบบไม่มีอะไรน่าสนใจ",
        "late_meals": "กินข้าวช้า",
        "heavy_crowds": "คนแน่นมาก",
        "balanced_pace": "จังหวะพอดี",
        "rewarding_walks": "เดินเมื่อมีสิ่งคุ้มค่าให้ชม",
        "meal_on_time": "กินตรงเวลา",
        "rest_breaks": "มีเวลาพัก",
        "low_walking": "เดินน้อย",
    },
}

ACCOMMODATION_TEXT = {
    "en": {"unknown": "Unknown", "not_booked": "Not booked", "booked": "Booked"},
    "th": {"unknown": "ยังไม่ทราบ", "not_booked": "ยังไม่ได้จอง", "booked": "จองแล้ว"},
}

DIMENSION_TEXT = {
    "en": {
        "group_preference_fit": "Group preference fit",
        "experience_value": "Expected experience value",
        "reward_vs_effort": "Reward versus effort",
        "time_fit": "Date / opening / best-time fit",
        "route_compatibility": "Route and cluster compatibility",
        "evidence_quality": "Evidence quality",
    },
    "th": {
        "group_preference_fit": "ความตรงกับความชอบของกลุ่ม",
        "experience_value": "คุณค่าประสบการณ์ที่คาดไว้",
        "reward_vs_effort": "ความคุ้มค่าเทียบกับแรงที่ใช้",
        "time_fit": "ความเหมาะกับวัน เวลาเปิด และช่วงชม",
        "route_compatibility": "ความเข้ากันของเส้นทางและกลุ่มสถานที่",
        "evidence_quality": "คุณภาพหลักฐาน",
    },
}

EXPLANATION_TEXT = {
    "en": {
        "group_preference_match": "Matches confirmed group preferences",
        "member_preferences_considered": "Uses supplied member preferences; missing profiles are not guessed",
        "city_icon_evidence": "Open data links this place to prominent landmark references",
        "learned_from_choices": "Similar to places you marked Must do / Interested / Maybe",
        "high_experience_potential": "Its city-independent category has strong experience potential",
        "broad_baseline_candidate": "Retained from the broad baseline even without a strong preference match",
        "protected_exploration": "Protected diversity slot from an under-seen experience family",
        "open_export_source": "Open, attributable catalog source",
        "preference_match": "Matches one or more explicit tags",
        "city_icon": "Kept visible as a City Icon; never forced into the plan",
        "regular_hours_present": "A regular schedule is present, but the trip date is not confirmed",
        "near_selected_cluster": "Geographically near a selected place; actual route is still unverified",
        "route_not_verified": "Walking, transit, transfers and effort are not routed yet",
        "ratings_not_enriched": "No licensed source rating or review sample has been enriched yet",
        "best_time_unconfirmed": "Best viewing time is unconfirmed",
        "opening_unconfirmed": "Opening hours are unconfirmed",
        "possible_duplicate": "Possible duplicate needs owner review",
        "access_unconfirmed": "Entrance and access instructions are unconfirmed",
        "near_selected_similar_experience": "Similar experience very near a selected place",
        "owner_rejected_without_reason": "Owner marked Not for trip without a reason",
        "too_crowded": "Owner marked it too crowded",
        "too_expensive": "Owner marked it too expensive",
        "too_tiring": "Owner marked it too tiring",
        "wrong_vibe": "Owner marked it the wrong vibe",
        "weak_value": "Owner marked its value too weak",
        "already_seen": "Owner has already seen it",
    },
    "th": {
        "group_preference_match": "ตรงกับความชอบของกลุ่มที่ยืนยันแล้ว",
        "member_preferences_considered": "ใช้เฉพาะความชอบสมาชิกที่กรอกไว้ และไม่เดาข้อมูลที่ขาด",
        "city_icon_evidence": "ข้อมูลเปิดเชื่อมสถานที่นี้กับแหล่งอ้างอิงแลนด์มาร์กเด่น",
        "learned_from_choices": "คล้ายสถานที่ที่คุณเลือก ต้องไป / สนใจ / อาจจะ",
        "high_experience_potential": "ประเภทสถานที่มีโอกาสให้ประสบการณ์ที่โดดเด่น",
        "broad_baseline_candidate": "เก็บไว้จากการค้นหาแบบกว้าง แม้ยังไม่ตรงความชอบชัดเจน",
        "protected_exploration": "ช่องสำรวจเพื่อรักษาความหลากหลายจากรูปแบบที่ยังเห็นน้อย",
        "open_export_source": "แหล่งข้อมูลเปิดที่ระบุที่มาได้",
        "preference_match": "ตรงกับแท็กที่ระบุอย่างน้อยหนึ่งข้อ",
        "city_icon": "แสดงไว้ในกลุ่มแลนด์มาร์ก แต่ไม่บังคับใส่แผน",
        "regular_hours_present": "มีเวลาปกติ แต่ยังไม่ยืนยันสำหรับวันเดินทาง",
        "near_selected_cluster": "อยู่ใกล้สถานที่ที่เลือกในเชิงพิกัด แต่ยังไม่ยืนยันเส้นทางจริง",
        "route_not_verified": "ยังไม่คำนวณการเดิน รถสาธารณะ การต่อรถ และแรงที่ใช้",
        "ratings_not_enriched": "ยังไม่มีเรตติ้งหรือตัวอย่างรีวิวจากแหล่งที่ได้รับอนุญาต",
        "best_time_unconfirmed": "ยังไม่ยืนยันช่วงเวลาที่ดีที่สุด",
        "opening_unconfirmed": "ยังไม่ยืนยันเวลาเปิด",
        "possible_duplicate": "อาจเป็นรายการซ้ำ ต้องให้เจ้าของตรวจสอบ",
        "access_unconfirmed": "ยังไม่ยืนยันทางเข้าและวิธีเข้าถึง",
        "near_selected_similar_experience": "ประสบการณ์คล้ายกันและอยู่ใกล้สถานที่ที่เลือกมาก",
        "owner_rejected_without_reason": "เจ้าของเลือกไม่เหมาะกับทริปโดยไม่ระบุเหตุผล",
        "too_crowded": "เจ้าของระบุว่าคนแน่นเกินไป",
        "too_expensive": "เจ้าของระบุว่าแพงเกินไป",
        "too_tiring": "เจ้าของระบุว่าเหนื่อยเกินไป",
        "wrong_vibe": "เจ้าของระบุว่าบรรยากาศไม่ตรง",
        "weak_value": "เจ้าของระบุว่าไม่คุ้ม",
        "already_seen": "เจ้าของเคยไปแล้ว",
    },
}

REJECTION_TEXT = {
    "en": {
        None: "No reason",
        "too_crowded": "Too crowded",
        "too_expensive": "Too expensive",
        "too_tiring": "Too tiring",
        "wrong_vibe": "Wrong vibe",
        "weak_value": "Weak value",
        "already_seen": "Already seen",
    },
    "th": {
        None: "ไม่ระบุเหตุผล",
        "too_crowded": "คนแน่นเกินไป",
        "too_expensive": "แพงเกินไป",
        "too_tiring": "เหนื่อยเกินไป",
        "wrong_vibe": "บรรยากาศไม่ตรง",
        "weak_value": "ไม่คุ้ม",
        "already_seen": "เคยไปแล้ว",
    },
}

CATEGORY_TEXT = {
    "en": {},
    "th": {
        "attraction": "สถานที่ท่องเที่ยว",
        "museum": "พิพิธภัณฑ์",
        "gallery": "แกลเลอรี",
        "viewpoint": "จุดชมวิว",
        "artwork": "งานศิลปะ",
        "theme_park": "สวนสนุก",
        "zoo": "สวนสัตว์",
        "aquarium": "พิพิธภัณฑ์สัตว์น้ำ",
        "historic": "สถานที่ประวัติศาสตร์",
        "place_of_worship": "ศาสนสถาน",
        "marketplace": "ตลาด",
        "theatre": "โรงละคร",
        "arts_centre": "ศูนย์ศิลปะ",
        "park": "สวนสาธารณะ",
        "garden": "สวน",
        "nature_reserve": "เขตอนุรักษ์ธรรมชาติ",
        "water_park": "สวนน้ำ",
        "sports_centre": "ศูนย์กีฬา",
        "spa": "สปา",
        "beach": "ชายหาด",
        "peak": "ยอดเขา",
        "mall": "ศูนย์การค้า",
        "department_store": "ห้างสรรพสินค้า",
        "tower": "หอคอย",
        "landmark": "แลนด์มาร์ก",
    },
}

OPTIMIZER_CODE_TEXT = {
    "th": {
        "OPENING_UNVERIFIED": "ยังไม่ยืนยันเวลาเปิดสำหรับวันเดินทาง",
        "ROUTE_UNVERIFIED": "ยังไม่มีเส้นทางและเวลาการเดินทางที่ยืนยันแล้ว",
        "ACCESS_UNVERIFIED": "ยังไม่ยืนยันทางเข้าและกฎการเข้าถึง",
        "ENTRANCE_UNVERIFIED": "ยังไม่ยืนยันจุดเข้าและวิธีเดินเข้า",
        "CLOSED_AT_AVAILABLE_TIME": "สถานที่ปิดในช่วงเวลาที่ใช้ได้",
        "SHOW_TYPE_UNAVAILABLE_AT_TIME": "ไม่มีรอบการแสดงที่ต้องการในเวลาที่ใช้ได้",
        "PLAIN_WALK_THRESHOLD": "การเดินทางธรรมดาเกินค่าที่ตั้งไว้",
        "LONG_TRANSFER_WALK": "ช่วงเดินทางด้วยการเดินไกลเกินค่าที่ตั้งไว้",
        "FATIGUE_THRESHOLD": "ภาระรวมของวันเกินค่าความสบาย",
        "TOURIST_TRAP_RISK": "มีความเสี่ยงเป็นกับดักนักท่องเที่ยว",
        "QUEUE_CAUSES_LATE_MEAL": "เวลารอทำให้มื้ออาหารช้าเกินช่วงที่ตั้งไว้",
        "WEAK_VALUE_FOR_EFFORT": "คุณค่าที่คาดหวังไม่คุ้มแรงเดินทาง",
        "TRANSPORT_MODE_PROHIBITED": "วิธีเดินทางนี้ไม่อนุญาต",
        "HEAT_AND_CYCLING_LOAD": "ความร้อนและภาระการปั่นเกินค่าที่ตั้งไว้",
        "EFFORT_OR_TIME_CONFLICT": "แรงที่ใช้หรือเวลาการเดินทางขัดกับตาราง",
        "RAIN_FALLBACK_ACTIVATED": "เปิดใช้แผนสำรองฝนและจัดวันใหม่แล้ว",
        "NO_VERIFIED_WEATHER_FALLBACK": "ยังไม่มีแผนสำรองอากาศที่ยืนยันแล้ว",
        "NO_TIME_CAPACITY": "ไม่มีเวลาว่างพอในทริป",
        "SCHEDULED": "จัดลงตารางได้หนึ่งครั้ง",
        "ROUTE_SNAPSHOT_MISSING": "ยังไม่มีชุดข้อมูลเส้นทางสำหรับสถานที่ที่เลือก",
        "DESTINATION_TIMEZONE_UNVERIFIED": "ยังไม่ยืนยันเขตเวลาของปลายทาง",
        "ACCOMMODATION_BASE_UNCONFIRMED": "ยังไม่มีฐานที่พักที่ยืนยันแล้ว",
        "FREE_TEXT_HARD_CONSTRAINT_NEEDS_STRUCTURED_CONFIRMATION": "ข้อจำเป็นแบบข้อความต้องยืนยันเป็นข้อมูลโครงสร้างก่อน",
        "NO_SELECTED_PLACE_COULD_BE_SCHEDULED": "ยังไม่มีสถานที่ที่เลือกใส่ตารางได้อย่างปลอดภัย",
    }
}

